name: Check Permissions

on:
  workflow_call:

jobs:
  authorize:
    runs-on: ubuntu-latest
    if: >-
      github.event_name == 'push' ||
      contains(fromJSON('["MEMBER", "OWNER", "COLLABORATOR"]'), github.event.pull_request.author_association) ||
      contains(github.event.pull_request.labels.*.name, 'ok-to-test')
    steps:
      - run: echo "CI authorized"
